# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetPadre(object):
    def setupUi(self, widgetPadre):
        widgetPadre.setObjectName("widgetPadre")
        widgetPadre.resize(1500, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widgetPadre.sizePolicy().hasHeightForWidth())
        widgetPadre.setSizePolicy(sizePolicy)
        widgetPadre.setMinimumSize(QtCore.QSize(1500, 900))
        widgetPadre.setStyleSheet("QWidget {\n"
"    background-color: #F2F2F2;;  /* Fondo color verde suave */\n"
"    border-radius: 10px;  /* Bordes redondeados */\n"
"    box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
"}\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(widgetPadre)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridFrame = QtWidgets.QFrame(widgetPadre)
        self.gridFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.gridFrame.setStyleSheet("background-color:  #F2F2F2;")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.Widget_informacion = QtWidgets.QFrame(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Widget_informacion.sizePolicy().hasHeightForWidth())
        self.Widget_informacion.setSizePolicy(sizePolicy)
        self.Widget_informacion.setMinimumSize(QtCore.QSize(450, 0))
        self.Widget_informacion.setStyleSheet("QFrame {\n"
"    background-color: #ACE08C;  /* Fondo color verde suave */\n"
"    border-radius: 10px;  /* Bordes redondeados */\n"
"    box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
"}\n"
"")
        self.Widget_informacion.setObjectName("Widget_informacion")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Widget_informacion)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(300, 65))
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_7.setStyleSheet("QLabel {\n"
"    font: bold 28px \"Playfair Display\", serif;  /* Fuente más elegante */\n"
"    background-color: rgba(255, 255, 255, 200);  /* Blanco con menos transparencia */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior más sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"    padding: 12px 20px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.2px;  /* Espaciado entre letras */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 10px rgba(0, 0, 0, 0.1);  /* Sombra sutil para efecto flotante */\n"
"}\n"
"")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(False)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_15 = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(500, 65))
        self.label_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_15.setStyleSheet("QLabel {\n"
"    font: bold 20px \"Georgia\", serif;  /* Fuente elegante */\n"
"    background-color: rgba(255, 255, 255, 150);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"    padding: 15px 25px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"    transition: all 0.3s ease-in-out;  /* Transición suave para el hover */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: rgba(255, 255, 255, 220);  /* Fondo menos transparente al pasar el mouse */\n"
"    border-bottom: 4px solid #285430;  /* Línea inferior más intensa */\n"
"    transform: scale(1.05);  /* Efecto de ligero aumento */\n"
"    box-shadow: 4px 6px 20px rgba(0, 0, 0, 0.3);  /* Sombra más pronunciada */\n"
"    color: #1b1b1b;  /* Color del texto más oscuro */\n"
"}\n"
"")
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_nombre = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nombre.sizePolicy().hasHeightForWidth())
        self.label_nombre.setSizePolicy(sizePolicy)
        self.label_nombre.setMinimumSize(QtCore.QSize(500, 50))
        self.label_nombre.setStyleSheet("QLabel {\n"
"    font: bold 18px \"Georgia\", serif;  /* Fuente aún más elegante y con mayor estilo */\n"
"    background-color: rgba(255, 255, 255, 80);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"    padding: 5px 15px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"}\n"
"")
        self.label_nombre.setObjectName("label_nombre")
        self.verticalLayout.addWidget(self.label_nombre, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.label_13 = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(500, 65))
        self.label_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_13.setStyleSheet("QLabel {\n"
"    font: bold 20px \"Georgia\", serif;  /* Fuente elegante */\n"
"    background-color: rgba(255, 255, 255, 150);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"    padding: 15px 25px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"    transition: all 0.3s ease-in-out;  /* Transición suave para el hover */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: rgba(255, 255, 255, 220);  /* Fondo menos transparente al pasar el mouse */\n"
"    border-bottom: 4px solid #285430;  /* Línea inferior más intensa */\n"
"    transform: scale(1.05);  /* Efecto de ligero aumento */\n"
"    box-shadow: 4px 6px 20px rgba(0, 0, 0, 0.3);  /* Sombra más pronunciada */\n"
"    color: #1b1b1b;  /* Color del texto más oscuro */\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_edad = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_edad.sizePolicy().hasHeightForWidth())
        self.label_edad.setSizePolicy(sizePolicy)
        self.label_edad.setMinimumSize(QtCore.QSize(500, 50))
        self.label_edad.setStyleSheet("QLabel {\n"
"    font: bold 18px \"Georgia\", serif;  /* Fuente aún más elegante y con mayor estilo */\n"
"    background-color: rgba(255, 255, 255, 80);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"padding: 5px 15px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"}\n"
"")
        self.label_edad.setObjectName("label_edad")
        self.verticalLayout.addWidget(self.label_edad)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(500, 65))
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_9.setStyleSheet("QLabel {\n"
"    font: bold 20px \"Georgia\", serif;  /* Fuente elegante */\n"
"    background-color: rgba(255, 255, 255, 150);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"    padding: 15px 25px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"    transition: all 0.3s ease-in-out;  /* Transición suave para el hover */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: rgba(255, 255, 255, 220);  /* Fondo menos transparente al pasar el mouse */\n"
"    border-bottom: 4px solid #285430;  /* Línea inferior más intensa */\n"
"    transform: scale(1.05);  /* Efecto de ligero aumento */\n"
"    box-shadow: 4px 6px 20px rgba(0, 0, 0, 0.3);  /* Sombra más pronunciada */\n"
"    color: #1b1b1b;  /* Color del texto más oscuro */\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_familia = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_familia.sizePolicy().hasHeightForWidth())
        self.label_familia.setSizePolicy(sizePolicy)
        self.label_familia.setMinimumSize(QtCore.QSize(500, 50))
        self.label_familia.setStyleSheet("QLabel {\n"
"    font: bold 18px \"Georgia\", serif;  /* Fuente aún más elegante y con mayor estilo */\n"
"    background-color: rgba(255, 255, 255, 80);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */padding: 5px 15px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"}\n"
"")
        self.label_familia.setObjectName("label_familia")
        self.verticalLayout.addWidget(self.label_familia)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.label_10 = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(500, 65))
        self.label_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_10.setStyleSheet("QLabel {\n"
"    font: bold 20px \"Georgia\", serif;  /* Fuente elegante */\n"
"    background-color: rgba(255, 255, 255, 150);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"    padding: 15px 25px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"    transition: all 0.3s ease-in-out;  /* Transición suave para el hover */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: rgba(255, 255, 255, 220);  /* Fondo menos transparente al pasar el mouse */\n"
"    border-bottom: 4px solid #285430;  /* Línea inferior más intensa */\n"
"    transform: scale(1.05);  /* Efecto de ligero aumento */\n"
"    box-shadow: 4px 6px 20px rgba(0, 0, 0, 0.3);  /* Sombra más pronunciada */\n"
"    color: #1b1b1b;  /* Color del texto más oscuro */\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_especie = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_especie.sizePolicy().hasHeightForWidth())
        self.label_especie.setSizePolicy(sizePolicy)
        self.label_especie.setMinimumSize(QtCore.QSize(500, 50))
        self.label_especie.setStyleSheet("QLabel {\n"
"    font: bold 18px \"Georgia\", serif;  /* Fuente aún más elegante y con mayor estilo */\n"
"    background-color: rgba(255, 255, 255, 80);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"    padding: 5px 15px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"}\n"
"")
        self.label_especie.setObjectName("label_especie")
        self.verticalLayout.addWidget(self.label_especie)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(500, 65))
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_5.setStyleSheet("QLabel {\n"
"    font: bold 20px \"Georgia\", serif;  /* Fuente elegante */\n"
"    background-color: rgba(255, 255, 255, 150);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"    padding: 15px 25px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"    transition: all 0.3s ease-in-out;  /* Transición suave para el hover */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: rgba(255, 255, 255, 220);  /* Fondo menos transparente al pasar el mouse */\n"
"    border-bottom: 4px solid #285430;  /* Línea inferior más intensa */\n"
"    transform: scale(1.05);  /* Efecto de ligero aumento */\n"
"    box-shadow: 4px 6px 20px rgba(0, 0, 0, 0.3);  /* Sombra más pronunciada */\n"
"    color: #1b1b1b;  /* Color del texto más oscuro */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_geografia = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_geografia.sizePolicy().hasHeightForWidth())
        self.label_geografia.setSizePolicy(sizePolicy)
        self.label_geografia.setMinimumSize(QtCore.QSize(500, 50))
        self.label_geografia.setStyleSheet("QLabel {\n"
"    font: bold 18px \"Georgia\", serif;  /* Fuente aún más elegante y con mayor estilo */\n"
"    background-color: rgba(255, 255, 255, 80);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"padding: 5px 15px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"}\n"
"")
        self.label_geografia.setObjectName("label_geografia")
        self.verticalLayout.addWidget(self.label_geografia)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(500, 65))
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3.setStyleSheet("QLabel {\n"
"    font: bold 20px \"Georgia\", serif;  /* Fuente elegante */\n"
"    background-color: rgba(255, 255, 255, 150);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"    padding: 15px 25px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"    transition: all 0.3s ease-in-out;  /* Transición suave para el hover */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: rgba(255, 255, 255, 220);  /* Fondo menos transparente al pasar el mouse */\n"
"    border-bottom: 4px solid #285430;  /* Línea inferior más intensa */\n"
"    transform: scale(1.05);  /* Efecto de ligero aumento */\n"
"    box-shadow: 4px 6px 20px rgba(0, 0, 0, 0.3);  /* Sombra más pronunciada */\n"
"    color: #1b1b1b;  /* Color del texto más oscuro */\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_floracion = QtWidgets.QLabel(self.Widget_informacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_floracion.sizePolicy().hasHeightForWidth())
        self.label_floracion.setSizePolicy(sizePolicy)
        self.label_floracion.setMinimumSize(QtCore.QSize(500, 50))
        self.label_floracion.setStyleSheet("QLabel {\n"
"    font: bold 18px \"Georgia\", serif;  /* Fuente aún más elegante y con mayor estilo */\n"
"    background-color: rgba(255, 255, 255, 80);  /* Fondo más transparente */\n"
"    border: none;  /* Sin bordes en los lados */\n"
"    border-bottom: 4px solid #3A5A40;  /* Línea inferior sutil y elegante */\n"
"    border-radius: 15px;  /* Bordes más suaves */\n"
"    color: #2b2b2b;  /* Color del texto */\n"
"padding: 5px 15px;  /* Espaciado más amplio */\n"
"    letter-spacing: 1.5px;  /* Espaciado entre letras más elegante */\n"
"    text-transform: capitalize;  /* Primera letra en mayúscula */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    box-shadow: 2px 4px 15px rgba(0, 0, 0, 0.2);  /* Sombra más pronunciada */\n"
"}\n"
"")
        self.label_floracion.setObjectName("label_floracion")
        self.verticalLayout.addWidget(self.label_floracion)
        self.gridLayout.addWidget(self.Widget_informacion, 0, 1, 1, 1)
        self.verticalFrame1 = QtWidgets.QFrame(self.gridFrame)
        self.verticalFrame1.setStyleSheet("background-color: #ACE08C;\n"
"")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridFrame1 = QtWidgets.QFrame(self.verticalFrame1)
        self.gridFrame1.setStyleSheet("background-color: #ACE08C;")
        self.gridFrame1.setObjectName("gridFrame1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.barra = QtWidgets.QProgressBar(self.gridFrame1)
        self.barra.setMinimumSize(QtCore.QSize(0, 50))
        self.barra.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #4A7C59;  /* Borde verde oscuro */\n"
"    border-radius: 10px;  /* Bordes redondeados */\n"
"    background-color: rgba(255, 255, 255, 150);  /* Fondo blanco con transparencia */\n"
"    text-align: center;  /* Centrar el texto */\n"
"    font: bold 14px \"Montserrat\";  /* Fuente moderna */\n"
"    color: #2b2b2b;  /* Color del texto oscuro */\n"
"    padding: 3px;  /* Espaciado interno */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #4A7C59, stop:1 #3A5A40);  /* Degradado verde oscuro */\n"
"    border-radius: 8px;  /* Bordes redondeados dentro de la barra */\n"
"    width: 10px;  /* Grosor del bloque de progreso */\n"
"}\n"
"")
        self.barra.setProperty("value", 24)
        self.barra.setObjectName("barra")
        self.gridLayout_6.addWidget(self.barra, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem6, 8, 0, 1, 1)
        self.label_camara = QtWidgets.QLabel(self.gridFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_camara.sizePolicy().hasHeightForWidth())
        self.label_camara.setSizePolicy(sizePolicy)
        self.label_camara.setMinimumSize(QtCore.QSize(0, 550))
        self.label_camara.setStyleSheet("QLabel {\n"
"    border: 5px solid #3A5A40;  /* Marco verde oscuro y elegante */\n"
"    border-radius: 20px;  /* Bordes más suaves y modernos */\n"
"    background-color: rgba(0, 0, 0, 80);  /* Fondo oscuro translúcido para un efecto premium */\n"
"    padding: 8px;  /* Espaciado interno para separación */\n"
"    \n"
"    /* Efecto de luz sutil */\n"
"    box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.4), \n"
"                0px 0px 15px rgba(58, 90, 64, 0.5);  \n"
"\n"
"    /* Borde interno brillante para mayor impacto */\n"
"    outline: 3px solid rgba(74, 124, 89, 0.5);  \n"
"}\n"
"")
        self.label_camara.setText("")
        self.label_camara.setObjectName("label_camara")
        self.gridLayout_6.addWidget(self.label_camara, 0, 0, 1, 1)
        self.btnSalir = QtWidgets.QPushButton(self.gridFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSalir.sizePolicy().hasHeightForWidth())
        self.btnSalir.setSizePolicy(sizePolicy)
        self.btnSalir.setMinimumSize(QtCore.QSize(500, 65))
        self.btnSalir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSalir.setStyleSheet("QPushButton {\n"
"    background-color: #4A7C59;  /* Verde oscuro para contraste */\n"
"    border-radius: 12px;  /* Bordes redondeados */\n"
"    padding: 10px 20px;  /* Espaciado interno */\n"
"    font: bold 30px \"Montserrat\";  /* Fuente moderna */\n"
"    color: white;  /* Texto en blanco */\n"
"    border: none;  /* Sin borde */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 0.2);  /* Sombra sutil */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3A5A40;  /* Cambio de color al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2C4A34;  /* Cambio de color al hacer clic */\n"
"    box-shadow: none;  /* Quita la sombra para efecto de presión */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/cerrar-sesion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalir.setIcon(icon)
        self.btnSalir.setIconSize(QtCore.QSize(40, 40))
        self.btnSalir.setObjectName("btnSalir")
        self.gridLayout_6.addWidget(self.btnSalir, 7, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem8, 3, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.gridFrame1)
        self.gridLayout.addWidget(self.verticalFrame1, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gridFrame, 0, 0, 1, 1)

        self.retranslateUi(widgetPadre)
        QtCore.QMetaObject.connectSlotsByName(widgetPadre)

    def retranslateUi(self, widgetPadre):
        _translate = QtCore.QCoreApplication.translate
        widgetPadre.setWindowTitle(_translate("widgetPadre", "Form"))
        self.label_7.setText(_translate("widgetPadre", "Información del árbol"))
        self.label_15.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\">Nombre del árbol</p></body></html>"))
        self.label_nombre.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">ssss</span></p></body></html>"))
        self.label_13.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\">Edad Estipulada</p></body></html>"))
        self.label_edad.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">sss</span></p></body></html>"))
        self.label_9.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Familia</span></p></body></html>"))
        self.label_familia.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\">ssss</p></body></html>"))
        self.label_10.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\">Especie</p></body></html>"))
        self.label_especie.setWhatsThis(_translate("widgetPadre", "<html><head/><body><p align=\"center\">sss</p></body></html>"))
        self.label_especie.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">TextLabel</span></p></body></html>"))
        self.label_5.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\">Distribución Geográfica</p></body></html>"))
        self.label_geografia.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">TextLabel</span></p></body></html>"))
        self.label_3.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\">Floración</p></body></html>"))
        self.label_floracion.setText(_translate("widgetPadre", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">TextLabel</span></p></body></html>"))
        self.btnSalir.setText(_translate("widgetPadre", "   Salir"))
